# Generated by Django 4.1.1 on 2022-09-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arizona_Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=30, null=True)),
                ('last_name', models.CharField(default=None, max_length=15, null=True)),
                ('state_id', models.IntegerField(default=None, max_length=42, null=True)),
                ('face_image', models.FileField(upload_to='uploads/%Y/%m/%d/%t')),
            ],
        ),
    ]
