# Generated by Django 4.1.1 on 2022-09-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="arizona_voter", name="face_image",),
        migrations.AlterField(
            model_name="arizona_voter",
            name="state_id",
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
