# Generated by Django 4.1.1 on 2022-09-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_arizona_voter_face_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arizona_voter",
            name="face_image",
            field=models.ImageField(default=None, upload_to="uploads"),
        ),
    ]
