# Generated by Django 4.1.1 on 2022-09-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_arizona_voter_face_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="California_Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                ("last_name", models.CharField(default=None, max_length=15, null=True)),
                ("state_id", models.CharField(default=None, max_length=7, null=True)),
                ("face_image", models.ImageField(default=None, upload_to="ca_voter")),
            ],
        ),
        migrations.AlterField(
            model_name="arizona_voter",
            name="face_image",
            field=models.ImageField(default=None, upload_to="az_voter"),
        ),
    ]
