# Generated by Django 4.1.1 on 2022-09-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_california_voter_alter_arizona_voter_face_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(default=None, max_length=9)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=15)),
                ('state', models.CharField(default=None, max_length=2)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(default=None, max_length=6)),
                ('image', models.ImageField(default=None, null=True, upload_to='system_reg/admin/images')),
                ('email', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('wallet_address', models.CharField(default=None, max_length=42)),
                ('super_admin', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyAmbassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(default=None, max_length=9)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=15)),
                ('state', models.CharField(default=None, max_length=2)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(default=None, max_length=6)),
                ('image', models.ImageField(default=None, null=True, upload_to='system_reg/az_voter/images')),
                ('email', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('wallet_address', models.CharField(default=None, max_length=42)),
                ('party_name', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(default=None, max_length=9)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=15)),
                ('state', models.CharField(default=None, max_length=2)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(default=None, max_length=6)),
                ('image', models.ImageField(default=None, null=True, upload_to='system_reg/voters/images')),
                ('gmm_file', models.FileField(null=True, upload_to='system_reg/voters/voice')),
                ('email', models.CharField(default=None, max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('wallet_address', models.CharField(default=None, max_length=42)),
                ('voting_token', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='arizona_voter',
            name='face_image',
        ),
        migrations.RemoveField(
            model_name='california_voter',
            name='face_image',
        ),
        migrations.AddField(
            model_name='arizona_voter',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='arizona_voter',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='arizona_voter',
            name='gender',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='arizona_voter',
            name='image',
            field=models.ImageField(default=None, upload_to='govt/az_voter'),
        ),
        migrations.AddField(
            model_name='arizona_voter',
            name='state',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='california_voter',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='california_voter',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='california_voter',
            name='gender',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='california_voter',
            name='image',
            field=models.ImageField(default=None, upload_to='govt/az_voter'),
        ),
        migrations.AddField(
            model_name='california_voter',
            name='state',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='arizona_voter',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='arizona_voter',
            name='last_name',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='arizona_voter',
            name='state_id',
            field=models.CharField(default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='california_voter',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='california_voter',
            name='last_name',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='california_voter',
            name='state_id',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
