# Generated by Django 4.1.1 on 2022-09-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_admin_partyambassador_voter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='partyambassador',
            name='image',
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='partyambassador',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state_id',
            field=models.CharField(default=None, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voting_token',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='wallet_address',
            field=models.CharField(default=None, max_length=42, null=True),
        ),
    ]
