# Generated by Django 4.1.1 on 2022-09-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_admin_image_remove_partyambassador_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voting_token',
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state_id',
            field=models.CharField(default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='voter',
            name='wallet_address',
            field=models.CharField(default=None, max_length=42),
        ),
    ]
