# Generated by Django 4.1.1 on 2022-10-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_voter_voting_token_alter_voter_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='tx_receipt',
            field=models.CharField(default=None, max_length=66),
        ),
        migrations.AddField(
            model_name='partyambassador',
            name='tx_receipt',
            field=models.CharField(default=None, max_length=66),
        ),
        migrations.AddField(
            model_name='voter',
            name='tx_receipt',
            field=models.CharField(default=None, max_length=66),
        ),
    ]
