# Generated by Django 4.1.1 on 2022-10-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_admin_wallet_address_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyambassador',
            name='tx_receipt',
        ),
    ]
