# Generated by Django 4.1.1 on 2022-11-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_voter_gmm_file_remove_voter_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='finger_print',
            field=models.ImageField(default=None, null=True, upload_to='test/voters_fingerprints'),
        ),
    ]
