# Generated by Django 4.1.1 on 2022-11-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_temp_finger_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=700),
        ),
    ]
