# Generated by Django 4.1.1 on 2022-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='admin',
            name='wallet_address_pk',
            field=models.CharField(default=None, max_length=170),
        ),
    ]
