# Generated by Django 4.1.1 on 2022-09-28 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_admin_partyambassador_voter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='campaign/images')),
                ('heading', models.CharField(default=None, max_length=20)),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('create_date', models.DateField(default=datetime.date(2022, 9, 28))),
                ('expire_date', models.DateField()),
                ('state', models.CharField(default=None, max_length=2, null=True)),
                ('transaction_id', models.CharField(default=None, max_length=66, null=True)),
                ('by_party_ambassador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.partyambassador')),
            ],
        ),
    ]
