# Generated by Django 4.1.1 on 2022-09-30 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='create_date',
            field=models.DateField(default=datetime.date(2022, 10, 1)),
        ),
    ]
