# Generated by Django 4.1.1 on 2022-10-14 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_alter_campaign_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='transaction_id',
            new_name='tx_receipt',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='by_party_ambassador',
            field=models.CharField(default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='create_date',
            field=models.DateField(default=datetime.date(2022, 10, 14)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 10, 21)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='campaign/images'),
        ),
    ]
