# Generated by Django 4.1.1 on 2022-10-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_rename_transaction_id_campaign_tx_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='heading',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
