# Generated by Django 4.1.1 on 2022-10-15 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_alter_campaign_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='create_date',
            field=models.DateField(default=datetime.date(2022, 10, 15)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 10, 22)),
        ),
    ]
