# Generated by Django 4.1.1 on 2022-11-20 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_alter_campaign_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='create_date',
            field=models.DateField(default=datetime.date(2022, 11, 20)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 11, 27)),
        ),
    ]
