# Generated by Django 4.1.1 on 2022-10-06 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=2)),
                ('total_votes', models.IntegerField(default=0)),
                ('created_date', models.DateField(default=datetime.date(2022, 10, 6), null=True)),
                ('expire_date', models.DateField(default=datetime.date(2022, 10, 13), null=True)),
                ('admin_creator_wallet_address', models.CharField(default=None, max_length=42)),
                ('candidates', models.IntegerField(default=0)),
                ('tx_receipt', models.CharField(default=None, max_length=66)),
            ],
        ),
    ]
