# Generated by Django 4.1.1 on 2022-10-06 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(default=None, max_length=9)),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(default=None, max_length=15)),
                ('state', models.CharField(default=None, max_length=2)),
                ('gender', models.CharField(default=None, max_length=6)),
                ('poll_name', models.CharField(default=None, max_length=50)),
                ('admin_creator_wallet_address', models.CharField(default=None, max_length=42)),
                ('tx_receipt', models.CharField(default=None, max_length=66)),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateField(default=datetime.date(2022, 10, 7), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 10, 14), null=True),
        ),
    ]
