# Generated by Django 4.1.1 on 2022-10-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_candidate_alter_poll_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='candidates',
            field=models.IntegerField(default=2),
        ),
    ]
