# Generated by Django 4.1.1 on 2022-10-08 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_poll_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='total_votes',
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateField(default=datetime.date(2022, 10, 8), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 10, 15), null=True),
        ),
    ]
