# Generated by Django 4.1.1 on 2022-10-12 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_poll_total_votes_alter_poll_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateField(default=datetime.date(2022, 10, 12), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 10, 19), null=True),
        ),
    ]
