# Generated by Django 4.1.1 on 2022-10-14 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_poll_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateField(default=datetime.date(2022, 10, 14), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 10, 21), null=True),
        ),
    ]
