# Generated by Django 4.1.1 on 2022-11-20 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_poll_created_date_alter_poll_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateField(default=datetime.date(2022, 11, 20), null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expire_date',
            field=models.DateField(default=datetime.date(2022, 11, 27), null=True),
        ),
    ]
